version: '3.7'

services:
  jmeter:
    build:
      context: .
      dockerfile: ./docker/jmeter.dockerfile
    volumes:
      - ./SCT_Jmeter/jmeter_data:/app/results   # Локальный путь к тестам в репозитории
      - ./SCT_Jmeter/jmeter_data:/app/test        # Локальный путь к результатам в репозитории
    networks:
      - network
    command: ["jmeter", "-n", "-t", "/app/jmeter_scripts/test.jmx", "-l", "/app/jmeter_data/test_results.jtl"]  # Пути внутри контейнера

  proxy:
    image: sct/neurorobin
    build:
      context: .
      dockerfile: ./docker/proxy.dockerfile
    ports:
      - 8000:80
    volumes:
      - config:/usr/local/nginx/conf
    networks:
      - network
    depends_on:
      - mock_server1
      - mock_server2
      - mock_server3
      - mock_server4
      - mock_server5
    restart: always

  mock_server1:
    image: sct/mock
    build:
      context: .
      dockerfile: ./docker/mock.dockerfile  
    ports:
      - "8001:8001" 
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8001  
      - MOCK_SERVER_NUMBER=1
    networks:
      - network  

  mock_server2:
    image: sct/mock
    build:
      context: .
      dockerfile: ./docker/mock.dockerfile  
    ports:
      - "8002:8002"
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8002  
      - MOCK_SERVER_NUMBER=2
    networks:
      - network

  mock_server3:  
    image: sct/mock
    build:
      context: .
      dockerfile: ./docker/mock.dockerfile  
    ports:
      - "8003:8003" 
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8003  
      - MOCK_SERVER_NUMBER=3
    networks:
      - network  

  mock_server4:  
    image: sct/mock
    build:
      context: .
      dockerfile: ./docker/mock.dockerfile  
    ports:
      - "8004:8004"
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8004  
      - MOCK_SERVER_NUMBER=4
    networks:
      - network

  mock_server5:
    image: sct/mock
    build:
      context: .
      dockerfile: ./docker/mock.dockerfile  
    ports:
      - "8005:8005"
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8005  
      - MOCK_SERVER_NUMBER=5
    networks:
      - network

volumes:
  config:

networks:
  network:
    driver: bridge
