version: '3.7'

services:
  proxy:
    image: sct/neurorobin
    build:
      context: .
      dockerfile: ./docker/proxy.dockerfile
    ports:
      - 8000:80
      - 3306:3306
    volumes:
      - config:/usr/local/nginx/conf
    networks:
      - network
    depends_on:
      - recalculator
      - mock_server1
      - mock_server2
      - mock_server3
      - mock_server4
      - mock_server5
      - mock_db1
      - mock_db2
    restart: always
    
  recalculator:
    image: sct/recalculator
    container_name: recalculator
    build: recalculator
    ports:
      - "7998:7998"
    volumes:
      - ./recalculator/weights:/src/weights
    networks:
      - network
    restart: on-failure

  mock_db1:
    build: mysql
    container_name: mock_db1
    environment:
      MYSQL_ROOT_PASSWORD: value
    volumes:
      - ./mysql/init1.sql:/docker-entrypoint-initdb.d/init.sql
      - mock_db1_data:/var/lib/mysql
    networks:
      - network

  mock_db2:
    build: mysql
    container_name: mock_db2
    environment:
      MYSQL_ROOT_PASSWORD: value
    volumes:
      - ./mysql/init2.sql:/docker-entrypoint-initdb.d/init.sql
      - mock_db2_data:/var/lib/mysql
    networks:
      - network

  mock_server1:
    image: sct/mock
    build:
      context: .
      dockerfile: ./docker/mock.dockerfile  
    ports:
      - "8001:8001" 
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8001  
      - MOCK_SERVER_NUMBER=1
    networks:
      - network  

  mock_server2:
    image: sct/mock
    build:
      context: .
      dockerfile: ./docker/mock.dockerfile  
    ports:
      - "8002:8002"
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8002  
      - MOCK_SERVER_NUMBER=2
    networks:
      - network

  mock_server3:  
    image: sct/mock
    build:
      context: .
      dockerfile: ./docker/mock.dockerfile  
    ports:
      - "8003:8003" 
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8003  
      - MOCK_SERVER_NUMBER=3
    networks:
      - network  

  mock_server4:  
    image: sct/mock
    build:
      context: .
      dockerfile: ./docker/mock.dockerfile  
    ports:
      - "8004:8004"
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8004  
      - MOCK_SERVER_NUMBER=4
    networks:
      - network

  mock_server5:
    image: sct/mock
    build:
      context: .
      dockerfile: ./docker/mock.dockerfile  
    ports:
      - "8005:8005"
    environment:
      - MOCK_API_HOST=${MOCK_API_HOST:-0.0.0.0}
      - MOCK_API_PORT=8005  
      - MOCK_SERVER_NUMBER=5
    networks:
      - network

volumes:
  config:
  mock_db1_data:
  mock_db2_data:

networks:
  network:
    driver: bridge
